/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicPosOrdersRouteImport } from './routes/api/public/pos/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosOrdersRoute = ApiPublicPosOrdersRouteImport.update({
  id: '/api/public/pos/orders',
  path: '/api/public/pos/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/order' | '/track' | '/api/public/orders' | '/api/public/pos/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/order' | '/track' | '/api/public/orders' | '/api/public/pos/orders'
  id:
    | '__root__'
    | '/'
    | '/order'
    | '/track'
    | '/api/public/orders'
    | '/api/public/pos/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRoute
  TrackRoute: typeof TrackRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicPosOrdersRoute: typeof ApiPublicPosOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos/orders': {
      id: '/api/public/pos/orders'
      path: '/api/public/pos/orders'
      fullPath: '/api/public/pos/orders'
      preLoaderRoute: typeof ApiPublicPosOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRoute,
  TrackRoute: TrackRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
  ApiPublicPosOrdersRoute: ApiPublicPosOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
